### ISSUE TITLE
Add gitlab-ci usage example

### ISSUE THREAD

**Issue by angelbarrera92** [sighupio/trivy-offline#1]
## Description

We want to see how you use this project in your CI pipelines. The scope of this issue is to have a clear example, (as it is already available for drone ci) that demonstrate how easy is to use this image in this CI system.

## Checklist

The CI target system here is Gitlab CI.

- [ ] Add a new markdown section in the README.md file: **CI Example - gitlab ci**
- [ ] Add a relative link from `what-we-do` section to the new  **CI Example - gitlab ci** section.

## Final note

If you like this project, don't forget to Star ⭐ it!
Enjoy #Hacktoberfest2020!

**Comment by o-c-e** [comment]
@angelbarrera92 mind if I work on it?

**Comment by angelbarrera92** [comment]
Hi @opencloudengineer, go for it! 

Thanks!
