### ISSUE TITLE
upgrade to trivy 0.37 and include the Java Index Database 

### ISSUE THREAD

**Issue by kforner** [sighupio/trivy-offline#12]
trivy 0.37 is out with a new feature (the Java Index Database) that should solve all problems related to JAR scanning and search.maven.org timeouts, cf https://github.com/aquasecurity/trivy/discussions/3518

It would be extremely useful (at least for me) to:
- upgrade trivy to 0.37
- include the Java Index Database (using --download-java-db-only and --skip-java-db-update) in the offline dbs.

I can do a PR if needed...

**Comment by kforner** [comment]
@ralgozino Does the Heart emoji mean yes?

**Comment by ralgozino** [comment]
Hello @kforner! yes please, go ahead.

Thank you!
