### ISSUE TITLE
cannot disable downloading the vunerabulity database in a disconnected environment

### ISSUE THREAD

**Issue by abdennour** [sighupio/trivy-offline#7]
i am running our CI/CD system in a disconnected environment.

I used the trivy-offline image, where i run this command : 

```sh
+ trivy image --exit-code 1 --input nexus-nexus-jd-snapshots-nodejs-sample-1-0-0-b5d0446
```
However, i got this error : 

```sh
2021-01-19T12:13:38.148Z	INFO	Need to update DB

2021-01-19T12:13:38.148Z	INFO	Downloading DB...

2021-01-19T12:14:08.151Z	FATAL	failed to download vulnerability DB: failed to download vulnerability DB: failed to list releases: Get "https://api.github.com/repos/aquasecurity/trivy-db/releases": dial tcp 140.x.y.z:443: i/o timeout

script returned exit code 1
```

How can i disable downloading the DB

**Comment by angelbarrera92** [comment]
> i am running our CI/CD system in a disconnected environment.
> 
> I used the trivy-offline image, where i run this command :
> 
> ```shell
> + trivy image --exit-code 1 --input nexus-nexus-jd-snapshots-nodejs-sample-1-0-0-b5d0446
> ```
> 
> However, i got this error :
> 
> ```shell
> 2021-01-19T12:13:38.148Z	INFO	Need to update DB
> 
> 2021-01-19T12:13:38.148Z	INFO	Downloading DB...
> 
> 2021-01-19T12:14:08.151Z	FATAL	failed to download vulnerability DB: failed to download vulnerability DB: failed to list releases: Get "https://api.github.com/repos/aquasecurity/trivy-db/releases": dial tcp 140.x.y.z:443: i/o timeout
> 
> script returned exit code 1
> ```
> 
> How can i disable downloading the DB

Ciao @abdennour!

Try running the same command with the `--skip-update` flag:

```bash
$ trivy --skip-update image --exit-code 1 --input nexus-nexus-jd-snapshots-nodejs-sample-1-0-0-b5d0446
```

**Comment by abdennour** [comment]
awesome! `--skip-update` did the job.
Thanks @angelbarrera92
