### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by filippobuletto** [sighupio/trivy-offline#8]
There is no license file! Please consider adding one.

**Comment by ralgozino** [comment]
Ciao @filippobuletto ! 

This repo is just a Dockerfile, what should we clarify with the license file?

thanks!

**Comment by omissis** [comment]
[LICENSE file added](https://github.com/sighupio/trivy-offline/commit/c864b90f19ce3d76eb790d8fa7c7860c65074bc1), thanks for heads up! Closing.
